name: Deploy Node APp
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Deploy to server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{secrets.SERVER_IP}}
          username: ${{secrets.USER_NAME}}
          key: ${{secrets.SERVER_SSH_KEY}}
          script: |
            cd /projects/my-apps/secure_account_management/backend/SecureAccounManagement/backend/
            git pull origin main
            npm install
            pm2 restart index

